/**
 * Regenerates the module-rules block inside firestore.rules (the section between
 * the GEN markers, inside `match /businesses/{bid}`).
 *
 *   npm run gen:rules
 *
 * Plain CommonJS with no TypeScript / src imports, so it runs on bare `node`
 * regardless of the repo's ESM setup. The generation LOGIC lives here and is
 * exercised from src/lib/rules/generate.test.ts, which also asserts that
 * DATA_MODELS below stays in sync with ALL_MANIFESTS[].dataModels — so this list
 * cannot silently drift from the module registry.
 */

'use strict';
const fs = require('node:fs');
const path = require('node:path');

const MARKER_START = '// GEN:MODULE-RULES:START — generated by scripts/gen-rules.ts; do not edit by hand';
const MARKER_END = '// GEN:MODULE-RULES:END';
const INDENT = '      '; // six spaces: inside match /businesses/{bid}

// Collections owned by catalog modules (mirrors each manifest's dataModels).
// Kept in registry order; the drift test asserts equality with ALL_MANIFESTS.
const MODULE_DATA_MODELS = [
  { collection: 'staff', module: 'staff', custom: true, legacyCaps: ['manage_staff'] },
  { collection: 'roles', module: 'roles', custom: true, legacyCaps: ['manage_roles'] },
];

// Collections not owned by a catalog module but living in the generated section.
const CORE_DATA_MODELS = [
  { collection: 'moduleEvents', module: 'roles', custom: true },
];

const DATA_MODELS = [...MODULE_DATA_MODELS, ...CORE_DATA_MODELS];

function legacyOr(caps) {
  return (caps || []).map((c) => ` || hasCap(bid, '${c}')`).join('');
}

function standardBlock(dm) {
  const legacy = legacyOr(dm.legacyCaps);
  return [
    `${INDENT}match /${dm.collection}/{docId} {`,
    `${INDENT}  allow read:           if can(bid, '${dm.module}', 'read')${legacy};`,
    `${INDENT}  allow create, update: if can(bid, '${dm.module}', 'write')${legacy};`,
    `${INDENT}  allow delete:         if can(bid, '${dm.module}', 'action')${legacy};`,
    `${INDENT}}`,
  ].join('\n');
}

// Build the inner (between-markers) content for the given dataModels + snippets.
function generateModuleRules(dataModels, snippets) {
  const seen = new Set();
  const blocks = [];
  for (const dm of dataModels) {
    if (seen.has(dm.collection)) continue;
    seen.add(dm.collection);
    if (dm.custom) {
      const snippet = snippets[dm.collection];
      if (snippet === undefined) {
        throw new Error(`Missing rules snippet for custom collection '${dm.collection}'`);
      }
      blocks.push(snippet.replace(/\s+$/, ''));
    } else {
      blocks.push(standardBlock(dm));
    }
  }
  return blocks.join('\n\n');
}

function spliceGeneratedRules(rulesText, generated) {
  const start = rulesText.indexOf(MARKER_START);
  const end = rulesText.indexOf(MARKER_END);
  if (start < 0 || end < 0 || end < start) {
    throw new Error('GEN markers not found (or out of order) in firestore.rules');
  }
  const lineStart = rulesText.lastIndexOf('\n', start) + 1;
  const indent = rulesText.slice(lineStart, start);
  const before = rulesText.slice(0, start);
  const after = rulesText.slice(end + MARKER_END.length);
  return `${before}${MARKER_START}\n\n${generated}\n\n${indent}${MARKER_END}${after}`;
}

function extractGeneratedRules(rulesText) {
  const start = rulesText.indexOf(MARKER_START);
  const end = rulesText.indexOf(MARKER_END);
  if (start < 0 || end < 0) throw new Error('GEN markers not found in firestore.rules');
  return rulesText.slice(start + MARKER_START.length, end).replace(/^\n+/, '').replace(/\n+[ \t]*$/, '');
}

function loadSnippets(snippetsDir) {
  const out = {};
  for (const file of fs.readdirSync(snippetsDir)) {
    if (!file.endsWith('.rules')) continue;
    out[file.replace(/\.rules$/, '')] = fs.readFileSync(path.join(snippetsDir, file), 'utf8');
  }
  return out;
}

function main() {
  const repoRoot = path.join(__dirname, '..');
  const rulesPath = path.join(repoRoot, 'firestore.rules');
  const snippets = loadSnippets(path.join(__dirname, 'rules-snippets'));
  const generated = generateModuleRules(DATA_MODELS, snippets);
  const current = fs.readFileSync(rulesPath, 'utf8');
  const next = spliceGeneratedRules(current, generated);
  if (next === current) {
    console.log('firestore.rules already up to date.');
    return;
  }
  fs.writeFileSync(rulesPath, next, 'utf8');
  console.log('firestore.rules regenerated.');
}

module.exports = {
  MARKER_START, MARKER_END, MODULE_DATA_MODELS, CORE_DATA_MODELS, DATA_MODELS,
  standardBlock, generateModuleRules, spliceGeneratedRules, extractGeneratedRules, loadSnippets,
};

if (require.main === module) main();
